/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadenasformulario;

import java.util.Locale;

/**
 *
 * @author ESTUDIANTE10
 */
public class cadenas extends javax.swing.JFrame {
    guiaMetodos.metodos ob1 = new guiaMetodos.metodos();
 String cadena1,cadena2,union,CADENA1,CADENA2,cadena1m,cadena2m,vocales1,vocales2;
 int c1,c2;
    /**
     * Creates new form cadenas
     */
    public cadenas() {
        super("cadenas   jhon monsalve");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areacadena1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        area1 = new javax.swing.JTextField();
        area2 = new javax.swing.JTextField();
        botonunion = new javax.swing.JButton();
        botonmayor = new javax.swing.JButton();
        botonmayus = new javax.swing.JButton();
        botonminus = new javax.swing.JButton();
        botonvocales = new javax.swing.JButton();
        areaunion = new javax.swing.JScrollPane();
        areaunion1 = new javax.swing.JTextArea();
        areamayor = new javax.swing.JScrollPane();
        areamayor2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areamayus = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaminus = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        areavocales = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadena 1");

        jLabel2.setText("Cadena 2");

        botonunion.setText("Union");
        botonunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonunionActionPerformed(evt);
            }
        });

        botonmayor.setText("Mayor");
        botonmayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmayorActionPerformed(evt);
            }
        });

        botonmayus.setText("Mayusculas");
        botonmayus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmayusActionPerformed(evt);
            }
        });

        botonminus.setText("Minusculas");
        botonminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonminusActionPerformed(evt);
            }
        });

        botonvocales.setText("Vocales");
        botonvocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvocalesActionPerformed(evt);
            }
        });

        areaunion1.setColumns(20);
        areaunion1.setRows(5);
        areaunion.setViewportView(areaunion1);

        areamayor2.setColumns(20);
        areamayor2.setRows(5);
        areamayor.setViewportView(areamayor2);

        areamayus.setColumns(20);
        areamayus.setRows(5);
        jScrollPane3.setViewportView(areamayus);

        areaminus.setColumns(20);
        areaminus.setRows(5);
        jScrollPane4.setViewportView(areaminus);

        areavocales.setColumns(20);
        areavocales.setRows(5);
        jScrollPane5.setViewportView(areavocales);

        javax.swing.GroupLayout areacadena1Layout = new javax.swing.GroupLayout(areacadena1);
        areacadena1.setLayout(areacadena1Layout);
        areacadena1Layout.setHorizontalGroup(
            areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areacadena1Layout.createSequentialGroup()
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areacadena1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(areacadena1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(areacadena1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(areacadena1Layout.createSequentialGroup()
                        .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(areacadena1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonmayor)
                                    .addComponent(botonunion)))
                            .addGroup(areacadena1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonmayus)
                                    .addComponent(botonminus)))
                            .addComponent(botonvocales, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane3)
                            .addComponent(areamayor)
                            .addComponent(areaunion))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        areacadena1Layout.setVerticalGroup(
            areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areacadena1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonunion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaunion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areamayor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(areacadena1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(botonmayus)))
                .addGap(18, 18, 18)
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areacadena1Layout.createSequentialGroup()
                        .addComponent(botonminus)
                        .addGap(17, 17, 17))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(areacadena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areacadena1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(botonvocales))
                    .addGroup(areacadena1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir!!!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areacadena1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(areacadena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonunionActionPerformed
        // TODO add your handling code here:
         cadena1 = area1.getText();
         cadena2 = area2.getText();
         union = ob1.concatenar(cadena1, cadena2);
        areaunion1.append(union);
    }//GEN-LAST:event_botonunionActionPerformed

    private void botonmayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmayorActionPerformed
        // TODO add your handling code here:
        cadena1 = area1.getText();
         cadena2 = area2.getText();
        c1 = ob1.longitudpalabra(cadena1);
        c2 = ob1.longitudpalabra(cadena2);
        if(c1<c2){
        areamayor2.append(cadena2);
        }
        if(c2<c1){ 
        areamayor2.append(cadena1);
        } 
    }//GEN-LAST:event_botonmayorActionPerformed

    private void botonmayusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmayusActionPerformed
        // TODO add your handling code here:
        CADENA1 = cadena1.toUpperCase();
        CADENA2 = cadena2.toUpperCase();
        areamayus.append(CADENA1);
        areamayus.append("  ");
        areamayus.append(CADENA2);
    }//GEN-LAST:event_botonmayusActionPerformed

    private void botonminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonminusActionPerformed
        // TODO add your handling code here:
        cadena1m = cadena1.toLowerCase();
        cadena2m = cadena2.toLowerCase();
        areaminus.append(cadena1m);
        areaminus.append("  ");
        areaminus.append(cadena2m);
    }//GEN-LAST:event_botonminusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        area1.setText(null);
        area2.setText(null);
        areaunion1.setText(null);
        areamayor2.setText(null);
        areamayus.setText(null);
        areaminus.setText(null);
        areavocales.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonvocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvocalesActionPerformed
        // TODO add your handling code here:
        vocales1 = ob1.quitarVocales(cadena1);
        vocales2 = ob1.quitarVocales(cadena2);
        areavocales.append(vocales1);
        areavocales.append("   ");
        areavocales.append(vocales2);
    }//GEN-LAST:event_botonvocalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadenas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area1;
    private javax.swing.JTextField area2;
    private javax.swing.JPanel areacadena1;
    private javax.swing.JScrollPane areamayor;
    private javax.swing.JTextArea areamayor2;
    private javax.swing.JTextArea areamayus;
    private javax.swing.JTextArea areaminus;
    private javax.swing.JScrollPane areaunion;
    private javax.swing.JTextArea areaunion1;
    private javax.swing.JTextArea areavocales;
    private javax.swing.JButton botonmayor;
    private javax.swing.JButton botonmayus;
    private javax.swing.JButton botonminus;
    private javax.swing.JButton botonunion;
    private javax.swing.JButton botonvocales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
